spring.config.import=optional:file:.env[.properties]
spring.application.name=driver-vehicle-service

server.port=8082


spring.mongodb.uri=${MONGO_URI}
spring.data.mongodb.uri=${MONGO_URI}

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

