spring.application.name=ride-management-service
server.port=8083

# MongoDB Connection (Spring Boot 4 uses spring.mongodb.uri)
spring.mongodb.uri=mongodb+srv://thissathissa918_db_user:Thissa1@userdetails.utvbpzy.mongodb.net/ride_management_db?appName=UserDetails


