spring.config.import=optional:file:.env[.properties]
spring.application.name=ride-management-service
server.port=8083

spring.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://localhost:27017/ride_db}}
spring.data.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://localhost:27017/ride_db}}

spring.cloud.openfeign.circuitbreaker.enabled=true

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
