spring.config.import=optional:file:.env[.properties]
server.port=8081
spring.application.name=account-service
spring.mongodb.uri=${MONGODB_URI:${MONGO_URI:mongodb://localhost:27017/account_db}}
spring.mongodb.database=account_db
spring.data.mongodb.uri=${MONGODB_URI:${MONGO_URI:mongodb://localhost:27017/account_db}}
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/