spring.config.import=optional:file:.env[.properties]
server.port=8081
spring.application.name=account-service
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=account_db
spring.data.mongodb.uri=${MONGODB_URI}