spring.config.import=optional:file:.env[.properties]
spring.application.name=fare-payment-service
server.port=8084

spring.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://localhost:27017/fare_payment_db}}
spring.data.mongodb.uri=${MONGO_URI:${MONGODB_URI:mongodb://localhost:27017/fare_payment_db}}

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
